<form method="post" action="<?php echo $this->url() ?>">
<table>
	<tr>
		<th>Description</th>
		<th>Action</th>
	</tr>
<?php foreach ($this->todos as $todo): ?>
	<tr>
		<td>
		<?php echo $this->escape($todo['name']) ?>
		<?php if ($todo['complete']): ?>
			<em>Completed on: <?php echo $todo['completed_display_date']; ?></em>
		<?php endif; ?>
		</td>
		<td>
			<?php if (!$todo['complete']): ?>
			<button type="submit" name="mark_complete" value="<?php echo $todo['id'] ?>"
				onclick="
				return confirm('Are you sure you want to mark this item complete?');
				"
			>
				Mark complete
			</button>
			<?php else: ?>
			&nbsp;
			<?php endif; ?>
		</td>
	</tr>
<?php endforeach; ?>
	<tr>
		<td>
			<input type="text" name="name">
		</td>
		<td>
			<button type="submit" name="insert_new" value="1">
				New task
			</button>
		</td>
	</tr>
</table>
</form>
